#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xmlrpc-c
Version  : 1.43.08
Release  : 2
URL      : https://sourceforge.net/projects/xmlrpc-c/files/Xmlrpc-c%20Super%20Stable/1.43.08/xmlrpc-c-1.43.08.tgz
Source0  : https://sourceforge.net/projects/xmlrpc-c/files/Xmlrpc-c%20Super%20Stable/1.43.08/xmlrpc-c-1.43.08.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause HPND
Requires: xmlrpc-c-bin = %{version}-%{release}
Requires: xmlrpc-c-lib = %{version}-%{release}
Requires: xmlrpc-c-license = %{version}-%{release}
BuildRequires : curl-dev
BuildRequires : ncurses-dev
BuildRequires : nghttp2-dev
BuildRequires : openssl-dev
BuildRequires : readline-dev

%description
This is the source code for XML-RPC for C/C++, called Xmlrpc-c for short.
XML-RPC for C/C++ is programming libraries and related tools to help you
write an XML-RPC server or client in C or C++.

%package bin
Summary: bin components for the xmlrpc-c package.
Group: Binaries
Requires: xmlrpc-c-license = %{version}-%{release}

%description bin
bin components for the xmlrpc-c package.


%package dev
Summary: dev components for the xmlrpc-c package.
Group: Development
Requires: xmlrpc-c-lib = %{version}-%{release}
Requires: xmlrpc-c-bin = %{version}-%{release}
Provides: xmlrpc-c-devel = %{version}-%{release}

%description dev
dev components for the xmlrpc-c package.


%package lib
Summary: lib components for the xmlrpc-c package.
Group: Libraries
Requires: xmlrpc-c-license = %{version}-%{release}

%description lib
lib components for the xmlrpc-c package.


%package license
Summary: license components for the xmlrpc-c package.
Group: Default

%description license
license components for the xmlrpc-c package.


%prep
%setup -q -n xmlrpc-c-1.43.08

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551203792
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1551203792
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xmlrpc-c
cp doc/COPYING %{buildroot}/usr/share/package-licenses/xmlrpc-c/doc_COPYING
cp lib/abyss/license.txt %{buildroot}/usr/share/package-licenses/xmlrpc-c/lib_abyss_license.txt
cp tools/binmode-rpc-kit/COPYING %{buildroot}/usr/share/package-licenses/xmlrpc-c/tools_binmode-rpc-kit_COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xmlrpc-c-config

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/xmlrpc-c/AbyssChanSwitch.hpp
/usr/include/xmlrpc-c/AbyssChanSwitchUnix.hpp
/usr/include/xmlrpc-c/AbyssEnvironment.hpp
/usr/include/xmlrpc-c/AbyssServer.hpp
/usr/include/xmlrpc-c/abyss.h
/usr/include/xmlrpc-c/abyss_reqhandler_xmlrpc.hpp
/usr/include/xmlrpc-c/abyss_unixsock.h
/usr/include/xmlrpc-c/abyss_winsock.h
/usr/include/xmlrpc-c/base.h
/usr/include/xmlrpc-c/base.hpp
/usr/include/xmlrpc-c/base64.hpp
/usr/include/xmlrpc-c/c_util.h
/usr/include/xmlrpc-c/client.h
/usr/include/xmlrpc-c/client.hpp
/usr/include/xmlrpc-c/client_global.h
/usr/include/xmlrpc-c/client_simple.hpp
/usr/include/xmlrpc-c/client_transport.hpp
/usr/include/xmlrpc-c/config.h
/usr/include/xmlrpc-c/girerr.hpp
/usr/include/xmlrpc-c/girmem.hpp
/usr/include/xmlrpc-c/inttypes.h
/usr/include/xmlrpc-c/json.h
/usr/include/xmlrpc-c/oldcppwrapper.hpp
/usr/include/xmlrpc-c/oldxmlrpc.h
/usr/include/xmlrpc-c/packetsocket.hpp
/usr/include/xmlrpc-c/registry.hpp
/usr/include/xmlrpc-c/server.h
/usr/include/xmlrpc-c/server_abyss.h
/usr/include/xmlrpc-c/server_abyss.hpp
/usr/include/xmlrpc-c/server_cgi.h
/usr/include/xmlrpc-c/server_pstream.hpp
/usr/include/xmlrpc-c/server_w32httpsys.h
/usr/include/xmlrpc-c/timeout.hpp
/usr/include/xmlrpc-c/transport.h
/usr/include/xmlrpc-c/util.h
/usr/include/xmlrpc-c/xml.hpp
/usr/lib64/libxmlrpc++.so
/usr/lib64/libxmlrpc.so
/usr/lib64/libxmlrpc_abyss++.so
/usr/lib64/libxmlrpc_abyss.so
/usr/lib64/libxmlrpc_client++.so
/usr/lib64/libxmlrpc_client.so
/usr/lib64/libxmlrpc_cpp.so
/usr/lib64/libxmlrpc_packetsocket.so
/usr/lib64/libxmlrpc_server++.so
/usr/lib64/libxmlrpc_server.so
/usr/lib64/libxmlrpc_server_abyss++.so
/usr/lib64/libxmlrpc_server_abyss.so
/usr/lib64/libxmlrpc_server_cgi++.so
/usr/lib64/libxmlrpc_server_cgi.so
/usr/lib64/libxmlrpc_server_pstream++.so
/usr/lib64/libxmlrpc_util++.so
/usr/lib64/libxmlrpc_util.so
/usr/lib64/libxmlrpc_xmlparse.so
/usr/lib64/libxmlrpc_xmltok.so
/usr/lib64/pkgconfig/xmlrpc++.pc
/usr/lib64/pkgconfig/xmlrpc.pc
/usr/lib64/pkgconfig/xmlrpc_abyss++.pc
/usr/lib64/pkgconfig/xmlrpc_abyss.pc
/usr/lib64/pkgconfig/xmlrpc_client++.pc
/usr/lib64/pkgconfig/xmlrpc_client.pc
/usr/lib64/pkgconfig/xmlrpc_expat.pc
/usr/lib64/pkgconfig/xmlrpc_server++.pc
/usr/lib64/pkgconfig/xmlrpc_server.pc
/usr/lib64/pkgconfig/xmlrpc_server_abyss.pc
/usr/lib64/pkgconfig/xmlrpc_server_cgi.pc
/usr/lib64/pkgconfig/xmlrpc_server_pstream++.pc
/usr/lib64/pkgconfig/xmlrpc_util++.pc
/usr/lib64/pkgconfig/xmlrpc_util.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxmlrpc++.so.8
/usr/lib64/libxmlrpc++.so.8.52
/usr/lib64/libxmlrpc.so.3
/usr/lib64/libxmlrpc.so.3.52
/usr/lib64/libxmlrpc_abyss++.so.8
/usr/lib64/libxmlrpc_abyss++.so.8.52
/usr/lib64/libxmlrpc_abyss.so.3
/usr/lib64/libxmlrpc_abyss.so.3.52
/usr/lib64/libxmlrpc_client++.so.8
/usr/lib64/libxmlrpc_client++.so.8.52
/usr/lib64/libxmlrpc_client.so.3
/usr/lib64/libxmlrpc_client.so.3.52
/usr/lib64/libxmlrpc_cpp.so.8
/usr/lib64/libxmlrpc_cpp.so.8.52
/usr/lib64/libxmlrpc_packetsocket.so.8
/usr/lib64/libxmlrpc_packetsocket.so.8.52
/usr/lib64/libxmlrpc_server++.so.8
/usr/lib64/libxmlrpc_server++.so.8.52
/usr/lib64/libxmlrpc_server.so.3
/usr/lib64/libxmlrpc_server.so.3.52
/usr/lib64/libxmlrpc_server_abyss++.so.8
/usr/lib64/libxmlrpc_server_abyss++.so.8.52
/usr/lib64/libxmlrpc_server_abyss.so.3
/usr/lib64/libxmlrpc_server_abyss.so.3.52
/usr/lib64/libxmlrpc_server_cgi++.so.8
/usr/lib64/libxmlrpc_server_cgi++.so.8.52
/usr/lib64/libxmlrpc_server_cgi.so.3
/usr/lib64/libxmlrpc_server_cgi.so.3.52
/usr/lib64/libxmlrpc_server_pstream++.so.8
/usr/lib64/libxmlrpc_server_pstream++.so.8.52
/usr/lib64/libxmlrpc_util++.so.8
/usr/lib64/libxmlrpc_util++.so.8.52
/usr/lib64/libxmlrpc_util.so.4
/usr/lib64/libxmlrpc_util.so.4.52
/usr/lib64/libxmlrpc_xmlparse.so.3
/usr/lib64/libxmlrpc_xmlparse.so.3.52
/usr/lib64/libxmlrpc_xmltok.so.3
/usr/lib64/libxmlrpc_xmltok.so.3.52

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xmlrpc-c/doc_COPYING
/usr/share/package-licenses/xmlrpc-c/lib_abyss_license.txt
/usr/share/package-licenses/xmlrpc-c/tools_binmode-rpc-kit_COPYING
